/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */

export interface DtoCreateSoundSlotRequest {
  /**
     * @minLength 1
     * @maxLength 2
     */
  key: string;
  /**
     * @minLength 1
     * @maxLength 64
     */
  label: string;
  sample_id?: number;
}
