/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */

/**
 * Visibility opsional (FR-VIS): "public" hanya boleh dipakai admin;
default "private" — lagu tidak tampil di Explore sampai dipublikasikan.
 */
export type DtoCreateSongRequestVisibility = typeof DtoCreateSongRequestVisibility[keyof typeof DtoCreateSongRequestVisibility];


export const DtoCreateSongRequestVisibility = {
  public: 'public',
  private: 'private',
} as const;
