/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import type { DtoCreateSongRequestVisibility } from './dtoCreateSongRequestVisibility';

export interface DtoCreateSongRequest {
  /**
     * @minimum 20
     * @maximum 400
     */
  bpm: number;
  /** IsSystemTemplate opsional: true = buat sebagai Song Template System.
  Hanya boleh dipakai admin (FR-ROLE). */
  is_system_template?: boolean;
  /**
     * @minLength 1
     * @maxLength 255
     */
  name: string;
  /** Visibility opsional (FR-VIS): "public" hanya boleh dipakai admin;
  default "private" — lagu tidak tampil di Explore sampai dipublikasikan. */
  visibility?: DtoCreateSongRequestVisibility;
}
