/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import type { DtoNullableString } from './dtoNullableString';

export interface DtoUpdateStepsRequest {
  steps?: DtoNullableString;
}
