/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */

export type DtoUpdateSongVisibilityRequestVisibility = typeof DtoUpdateSongVisibilityRequestVisibility[keyof typeof DtoUpdateSongVisibilityRequestVisibility];


export const DtoUpdateSongVisibilityRequestVisibility = {
  public: 'public',
  private: 'private',
} as const;
