/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */

/**
 * NextMode=nil → tidak berubah. Nilai valid: "order" (lanjut ke section
berikutnya), "target" (lanjut ke next_section_id), "end" (ending/berhenti).
 */
export type DtoUpdateSectionRequestNextMode = typeof DtoUpdateSectionRequestNextMode[keyof typeof DtoUpdateSectionRequestNextMode];


export const DtoUpdateSectionRequestNextMode = {
  order: 'order',
  target: 'target',
  end: 'end',
} as const;
