/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import type { DtoNullableInt16 } from './dtoNullableInt16';

export interface DtoUpdateSectionRequest {
  bpm_override?: DtoNullableInt16;
  /**
     * @minLength 1
     * @maxLength 255
     */
  name?: string;
}
