/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */

export type GetAuthGoogleParams = {
/**
 * 1 = mode link (akun sudah login)
 */
link?: number;
};
