/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */

export type PostSamplesBody = {
  /** File audio .wav */
  file: Blob;
  /** Nama sample */
  name: string;
  /** Part (rebana1-4, bass) */
  part: string;
  /** true = Sample Template System (hanya admin) */
  is_system_template?: boolean;
};
