/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoErrorResponse,
  DtoRenameSampleRequest,
  DtoSuccessResponse,
  GetSamplesParams,
  GetSamplesTemplatesParams,
  PostSamplesBody
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getSamplesResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSamplesResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getSamplesResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getSamplesResponseSuccess = (getSamplesResponse200) & {
  headers: Headers;
};
export type getSamplesResponseError = (getSamplesResponse400 | getSamplesResponse401) & {
  headers: Headers;
};

export type getSamplesResponse = (getSamplesResponseSuccess | getSamplesResponseError)

export const getGetSamplesUrl = (params?: GetSamplesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/samples?${stringifiedParams}` : `/samples`
}

/**
 * Daftar Sample milik user login (filter opsional ?part=)
 * @summary List user samples
 */
export const getSamples = async (params?: GetSamplesParams, options?: RequestInit): Promise<getSamplesResponse> => {

  return customInstance<getSamplesResponse>(getGetSamplesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSamplesQueryKey = (params?: GetSamplesParams,) => {
    return [
    `/samples`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSamplesQueryOptions = <TData = Awaited<ReturnType<typeof getSamples>>, TError = DtoErrorResponse>(params?: GetSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamples>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSamplesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSamples>>> = ({ signal }) => getSamples(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSamples>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSamplesQueryResult = NonNullable<Awaited<ReturnType<typeof getSamples>>>
export type GetSamplesQueryError = DtoErrorResponse


export function useGetSamples<TData = Awaited<ReturnType<typeof getSamples>>, TError = DtoErrorResponse>(
 params: undefined |  GetSamplesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamples>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSamples>>,
          TError,
          Awaited<ReturnType<typeof getSamples>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSamples<TData = Awaited<ReturnType<typeof getSamples>>, TError = DtoErrorResponse>(
 params?: GetSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamples>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSamples>>,
          TError,
          Awaited<ReturnType<typeof getSamples>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSamples<TData = Awaited<ReturnType<typeof getSamples>>, TError = DtoErrorResponse>(
 params?: GetSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamples>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List user samples
 */

export function useGetSamples<TData = Awaited<ReturnType<typeof getSamples>>, TError = DtoErrorResponse>(
 params?: GetSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamples>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSamplesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postSamplesResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postSamplesResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postSamplesResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postSamplesResponse413 = {
  data: DtoErrorResponse
  status: 413
}

export type postSamplesResponse415 = {
  data: DtoErrorResponse
  status: 415
}

export type postSamplesResponseSuccess = (postSamplesResponse201) & {
  headers: Headers;
};
export type postSamplesResponseError = (postSamplesResponse400 | postSamplesResponse401 | postSamplesResponse413 | postSamplesResponse415) & {
  headers: Headers;
};

export type postSamplesResponse = (postSamplesResponseSuccess | postSamplesResponseError)

export const getPostSamplesUrl = () => {




  return `/samples`
}

/**
 * Upload file audio .wav (maks 5MB) sebagai Sample milik user
 * @summary Upload sample
 */
export const postSamples = async (postSamplesBody?: PostSamplesBody, options?: RequestInit): Promise<postSamplesResponse> => {
    const formData = new FormData();
if(postSamplesBody?.file !== undefined) {
 formData.append(`file`, postSamplesBody.file);
 }
if(postSamplesBody?.name !== undefined) {
 formData.append(`name`, postSamplesBody.name);
 }
if(postSamplesBody?.part !== undefined) {
 formData.append(`part`, postSamplesBody.part);
 }

  return customInstance<postSamplesResponse>(getPostSamplesUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getPostSamplesMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSamples>>, TError,{data?: PostSamplesBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postSamples>>, TError,{data?: PostSamplesBody}, TContext> => {

const mutationKey = ['postSamples'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSamples>>, {data?: PostSamplesBody}> = (props) => {
          const {data} = props ?? {};

          return  postSamples(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSamplesMutationResult = NonNullable<Awaited<ReturnType<typeof postSamples>>>
    export type PostSamplesMutationBody = PostSamplesBody | undefined
    export type PostSamplesMutationError = DtoErrorResponse

    /**
 * @summary Upload sample
 */
export const usePostSamples = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSamples>>, TError,{data?: PostSamplesBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSamples>>,
        TError,
        {data?: PostSamplesBody},
        TContext
      > => {
      return useMutation(getPostSamplesMutationOptions(options), queryClient);
    }
    export type getSamplesTemplatesResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSamplesTemplatesResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type getSamplesTemplatesResponseSuccess = (getSamplesTemplatesResponse200) & {
  headers: Headers;
};
export type getSamplesTemplatesResponseError = (getSamplesTemplatesResponse400) & {
  headers: Headers;
};

export type getSamplesTemplatesResponse = (getSamplesTemplatesResponseSuccess | getSamplesTemplatesResponseError)

export const getGetSamplesTemplatesUrl = (params?: GetSamplesTemplatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/samples/templates?${stringifiedParams}` : `/samples/templates`
}

/**
 * Daftar Sample Template System (read-only, filter opsional ?part=) — dapat diakses Guest
 * @summary List sample templates
 */
export const getSamplesTemplates = async (params?: GetSamplesTemplatesParams, options?: RequestInit): Promise<getSamplesTemplatesResponse> => {

  return customInstance<getSamplesTemplatesResponse>(getGetSamplesTemplatesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSamplesTemplatesQueryKey = (params?: GetSamplesTemplatesParams,) => {
    return [
    `/samples/templates`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSamplesTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getSamplesTemplates>>, TError = DtoErrorResponse>(params?: GetSamplesTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSamplesTemplatesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSamplesTemplates>>> = ({ signal }) => getSamplesTemplates(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSamplesTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSamplesTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getSamplesTemplates>>>
export type GetSamplesTemplatesQueryError = DtoErrorResponse


export function useGetSamplesTemplates<TData = Awaited<ReturnType<typeof getSamplesTemplates>>, TError = DtoErrorResponse>(
 params: undefined |  GetSamplesTemplatesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSamplesTemplates>>,
          TError,
          Awaited<ReturnType<typeof getSamplesTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSamplesTemplates<TData = Awaited<ReturnType<typeof getSamplesTemplates>>, TError = DtoErrorResponse>(
 params?: GetSamplesTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSamplesTemplates>>,
          TError,
          Awaited<ReturnType<typeof getSamplesTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSamplesTemplates<TData = Awaited<ReturnType<typeof getSamplesTemplates>>, TError = DtoErrorResponse>(
 params?: GetSamplesTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List sample templates
 */

export function useGetSamplesTemplates<TData = Awaited<ReturnType<typeof getSamplesTemplates>>, TError = DtoErrorResponse>(
 params?: GetSamplesTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSamplesTemplatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type putSamplesIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSamplesIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSamplesIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSamplesIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSamplesIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSamplesIdResponseSuccess = (putSamplesIdResponse200) & {
  headers: Headers;
};
export type putSamplesIdResponseError = (putSamplesIdResponse400 | putSamplesIdResponse401 | putSamplesIdResponse403 | putSamplesIdResponse404) & {
  headers: Headers;
};

export type putSamplesIdResponse = (putSamplesIdResponseSuccess | putSamplesIdResponseError)

export const getPutSamplesIdUrl = (id: number,) => {




  return `/samples/${id}`
}

/**
 * Ganti nama Sample milik user. Ditolak 403 untuk Sample Template System.
 * @summary Rename sample
 */
export const putSamplesId = async (id: number,
    dtoRenameSampleRequest: DtoRenameSampleRequest, options?: RequestInit): Promise<putSamplesIdResponse> => {

  return customInstance<putSamplesIdResponse>(getPutSamplesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoRenameSampleRequest,)
  }
);}




export const getPutSamplesIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSamplesId>>, TError,{id: number;data: DtoRenameSampleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSamplesId>>, TError,{id: number;data: DtoRenameSampleRequest}, TContext> => {

const mutationKey = ['putSamplesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSamplesId>>, {id: number;data: DtoRenameSampleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSamplesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSamplesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putSamplesId>>>
    export type PutSamplesIdMutationBody = DtoRenameSampleRequest
    export type PutSamplesIdMutationError = DtoErrorResponse

    /**
 * @summary Rename sample
 */
export const usePutSamplesId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSamplesId>>, TError,{id: number;data: DtoRenameSampleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSamplesId>>,
        TError,
        {id: number;data: DtoRenameSampleRequest},
        TContext
      > => {
      return useMutation(getPutSamplesIdMutationOptions(options), queryClient);
    }
    export type deleteSamplesIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteSamplesIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteSamplesIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type deleteSamplesIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteSamplesIdResponse409 = {
  data: DtoErrorResponse
  status: 409
}

export type deleteSamplesIdResponseSuccess = (deleteSamplesIdResponse200) & {
  headers: Headers;
};
export type deleteSamplesIdResponseError = (deleteSamplesIdResponse401 | deleteSamplesIdResponse403 | deleteSamplesIdResponse404 | deleteSamplesIdResponse409) & {
  headers: Headers;
};

export type deleteSamplesIdResponse = (deleteSamplesIdResponseSuccess | deleteSamplesIdResponseError)

export const getDeleteSamplesIdUrl = (id: number,) => {




  return `/samples/${id}`
}

/**
 * Hapus Sample milik user. Ditolak 409 bila masih direferensikan SoundSlot, 403 untuk template.
 * @summary Delete sample
 */
export const deleteSamplesId = async (id: number, options?: RequestInit): Promise<deleteSamplesIdResponse> => {

  return customInstance<deleteSamplesIdResponse>(getDeleteSamplesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSamplesIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSamplesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSamplesId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteSamplesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSamplesId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteSamplesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSamplesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSamplesId>>>

    export type DeleteSamplesIdMutationError = DtoErrorResponse

    /**
 * @summary Delete sample
 */
export const useDeleteSamplesId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSamplesId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSamplesId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteSamplesIdMutationOptions(options), queryClient);
    }
    export type getSamplesIdPlaybackUrlResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSamplesIdPlaybackUrlResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type getSamplesIdPlaybackUrlResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getSamplesIdPlaybackUrlResponseSuccess = (getSamplesIdPlaybackUrlResponse200) & {
  headers: Headers;
};
export type getSamplesIdPlaybackUrlResponseError = (getSamplesIdPlaybackUrlResponse403 | getSamplesIdPlaybackUrlResponse404) & {
  headers: Headers;
};

export type getSamplesIdPlaybackUrlResponse = (getSamplesIdPlaybackUrlResponseSuccess | getSamplesIdPlaybackUrlResponseError)

export const getGetSamplesIdPlaybackUrlUrl = (id: number,) => {




  return `/samples/${id}/playback-url`
}

/**
 * Signed URL sementara (60 menit) untuk memutar file audio. Template dapat diakses Guest.
 * @summary Get sample playback URL
 */
export const getSamplesIdPlaybackUrl = async (id: number, options?: RequestInit): Promise<getSamplesIdPlaybackUrlResponse> => {

  return customInstance<getSamplesIdPlaybackUrlResponse>(getGetSamplesIdPlaybackUrlUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSamplesIdPlaybackUrlQueryKey = (id: number,) => {
    return [
    `/samples/${id}/playback-url`
    ] as const;
    }


export const getGetSamplesIdPlaybackUrlQueryOptions = <TData = Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError = DtoErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSamplesIdPlaybackUrlQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>> = ({ signal }) => getSamplesIdPlaybackUrl(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSamplesIdPlaybackUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>>
export type GetSamplesIdPlaybackUrlQueryError = DtoErrorResponse


export function useGetSamplesIdPlaybackUrl<TData = Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError = DtoErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>,
          TError,
          Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSamplesIdPlaybackUrl<TData = Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>,
          TError,
          Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSamplesIdPlaybackUrl<TData = Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get sample playback URL
 */

export function useGetSamplesIdPlaybackUrl<TData = Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSamplesIdPlaybackUrl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSamplesIdPlaybackUrlQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






