/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateSoundSlotRequest,
  DtoErrorResponse,
  DtoSuccessResponse,
  DtoUpdateSoundSlotRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postSectionPartsIdSoundSlotsResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postSectionPartsIdSoundSlotsResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postSectionPartsIdSoundSlotsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postSectionPartsIdSoundSlotsResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type postSectionPartsIdSoundSlotsResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type postSectionPartsIdSoundSlotsResponseSuccess = (postSectionPartsIdSoundSlotsResponse201) & {
  headers: Headers;
};
export type postSectionPartsIdSoundSlotsResponseError = (postSectionPartsIdSoundSlotsResponse400 | postSectionPartsIdSoundSlotsResponse401 | postSectionPartsIdSoundSlotsResponse403 | postSectionPartsIdSoundSlotsResponse404) & {
  headers: Headers;
};

export type postSectionPartsIdSoundSlotsResponse = (postSectionPartsIdSoundSlotsResponseSuccess | postSectionPartsIdSoundSlotsResponseError)

export const getPostSectionPartsIdSoundSlotsUrl = (id: number,) => {




  return `/section-parts/${id}/sound-slots`
}

/**
 * Tambah SoundSlot (jenis bunyi) pada SectionPart — key unik per SectionPart
 * @summary Create sound slot
 */
export const postSectionPartsIdSoundSlots = async (id: number,
    dtoCreateSoundSlotRequest: DtoCreateSoundSlotRequest, options?: RequestInit): Promise<postSectionPartsIdSoundSlotsResponse> => {

  return customInstance<postSectionPartsIdSoundSlotsResponse>(getPostSectionPartsIdSoundSlotsUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateSoundSlotRequest,)
  }
);}




export const getPostSectionPartsIdSoundSlotsMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSectionPartsIdSoundSlots>>, TError,{id: number;data: DtoCreateSoundSlotRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postSectionPartsIdSoundSlots>>, TError,{id: number;data: DtoCreateSoundSlotRequest}, TContext> => {

const mutationKey = ['postSectionPartsIdSoundSlots'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSectionPartsIdSoundSlots>>, {id: number;data: DtoCreateSoundSlotRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postSectionPartsIdSoundSlots(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSectionPartsIdSoundSlotsMutationResult = NonNullable<Awaited<ReturnType<typeof postSectionPartsIdSoundSlots>>>
    export type PostSectionPartsIdSoundSlotsMutationBody = DtoCreateSoundSlotRequest
    export type PostSectionPartsIdSoundSlotsMutationError = DtoErrorResponse

    /**
 * @summary Create sound slot
 */
export const usePostSectionPartsIdSoundSlots = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSectionPartsIdSoundSlots>>, TError,{id: number;data: DtoCreateSoundSlotRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSectionPartsIdSoundSlots>>,
        TError,
        {id: number;data: DtoCreateSoundSlotRequest},
        TContext
      > => {
      return useMutation(getPostSectionPartsIdSoundSlotsMutationOptions(options), queryClient);
    }
    export type putSoundSlotsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSoundSlotsIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSoundSlotsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSoundSlotsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSoundSlotsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSoundSlotsIdResponseSuccess = (putSoundSlotsIdResponse200) & {
  headers: Headers;
};
export type putSoundSlotsIdResponseError = (putSoundSlotsIdResponse400 | putSoundSlotsIdResponse401 | putSoundSlotsIdResponse403 | putSoundSlotsIdResponse404) & {
  headers: Headers;
};

export type putSoundSlotsIdResponse = (putSoundSlotsIdResponseSuccess | putSoundSlotsIdResponseError)

export const getPutSoundSlotsIdUrl = (id: number,) => {




  return `/sound-slots/${id}`
}

/**
 * Update label/key/sample_id (sample_id null untuk melepas referensi). Ubah key yang masih dipakai steps ditolak 400.
 * @summary Update sound slot
 */
export const putSoundSlotsId = async (id: number,
    dtoUpdateSoundSlotRequest: DtoUpdateSoundSlotRequest, options?: RequestInit): Promise<putSoundSlotsIdResponse> => {

  return customInstance<putSoundSlotsIdResponse>(getPutSoundSlotsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoUpdateSoundSlotRequest,)
  }
);}




export const getPutSoundSlotsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSoundSlotsId>>, TError,{id: number;data: DtoUpdateSoundSlotRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSoundSlotsId>>, TError,{id: number;data: DtoUpdateSoundSlotRequest}, TContext> => {

const mutationKey = ['putSoundSlotsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSoundSlotsId>>, {id: number;data: DtoUpdateSoundSlotRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSoundSlotsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSoundSlotsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putSoundSlotsId>>>
    export type PutSoundSlotsIdMutationBody = DtoUpdateSoundSlotRequest
    export type PutSoundSlotsIdMutationError = DtoErrorResponse

    /**
 * @summary Update sound slot
 */
export const usePutSoundSlotsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSoundSlotsId>>, TError,{id: number;data: DtoUpdateSoundSlotRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSoundSlotsId>>,
        TError,
        {id: number;data: DtoUpdateSoundSlotRequest},
        TContext
      > => {
      return useMutation(getPutSoundSlotsIdMutationOptions(options), queryClient);
    }
    export type deleteSoundSlotsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteSoundSlotsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteSoundSlotsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type deleteSoundSlotsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteSoundSlotsIdResponse409 = {
  data: DtoErrorResponse
  status: 409
}

export type deleteSoundSlotsIdResponseSuccess = (deleteSoundSlotsIdResponse200) & {
  headers: Headers;
};
export type deleteSoundSlotsIdResponseError = (deleteSoundSlotsIdResponse401 | deleteSoundSlotsIdResponse403 | deleteSoundSlotsIdResponse404 | deleteSoundSlotsIdResponse409) & {
  headers: Headers;
};

export type deleteSoundSlotsIdResponse = (deleteSoundSlotsIdResponseSuccess | deleteSoundSlotsIdResponseError)

export const getDeleteSoundSlotsIdUrl = (id: number,) => {




  return `/sound-slots/${id}`
}

/**
 * Hapus SoundSlot. Ditolak 409 bila key masih dipakai di steps.
 * @summary Delete sound slot
 */
export const deleteSoundSlotsId = async (id: number, options?: RequestInit): Promise<deleteSoundSlotsIdResponse> => {

  return customInstance<deleteSoundSlotsIdResponse>(getDeleteSoundSlotsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSoundSlotsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSoundSlotsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSoundSlotsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteSoundSlotsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSoundSlotsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteSoundSlotsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSoundSlotsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSoundSlotsId>>>

    export type DeleteSoundSlotsIdMutationError = DtoErrorResponse

    /**
 * @summary Delete sound slot
 */
export const useDeleteSoundSlotsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSoundSlotsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSoundSlotsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteSoundSlotsIdMutationOptions(options), queryClient);
    }
