/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppProjectRouteImport } from './routes/_app/project'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as TemplatesSongIdRouteImport } from './routes/templates.$songId'
import { Route as AppProjectIndexRouteImport } from './routes/_app/project.index'
import { Route as AppProjectSamplesRouteImport } from './routes/_app/project.samples'
import { Route as SongsSongIdIndexRouteImport } from './routes/songs.$songId.index'
import { Route as SongsSongIdPlayRouteImport } from './routes/songs.$songId.play'
import { Route as SongsSongIdSectionsSectionIdRouteImport } from './routes/songs.$songId.sections.$sectionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectRoute = AppProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => AppRoute,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSongIdRoute = TemplatesSongIdRouteImport.update({
  id: '/templates/$songId',
  path: '/templates/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIndexRoute = AppProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectRoute,
} as any)
const AppProjectSamplesRoute = AppProjectSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AppProjectRoute,
} as any)
const SongsSongIdIndexRoute = SongsSongIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SongsSongIdRoute,
} as any)
const SongsSongIdPlayRoute = SongsSongIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => SongsSongIdRoute,
} as any)
const SongsSongIdSectionsSectionIdRoute =
  SongsSongIdSectionsSectionIdRouteImport.update({
    id: '/sections/$sectionId',
    path: '/sections/$sectionId',
    getParentRoute: () => SongsSongIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/explore': typeof AppExploreRoute
  '/profile': typeof AppProfileRoute
  '/project': typeof AppProjectRouteWithChildren
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/templates/$songId': typeof TemplatesSongIdRoute
  '/project/samples': typeof AppProjectSamplesRoute
  '/songs/$songId/play': typeof SongsSongIdPlayRoute
  '/project/': typeof AppProjectIndexRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/sections/$sectionId': typeof SongsSongIdSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/explore': typeof AppExploreRoute
  '/profile': typeof AppProfileRoute
  '/templates/$songId': typeof TemplatesSongIdRoute
  '/': typeof AppIndexRoute
  '/project/samples': typeof AppProjectSamplesRoute
  '/songs/$songId/play': typeof SongsSongIdPlayRoute
  '/project': typeof AppProjectIndexRoute
  '/songs/$songId': typeof SongsSongIdIndexRoute
  '/songs/$songId/sections/$sectionId': typeof SongsSongIdSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/project': typeof AppProjectRouteWithChildren
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/templates/$songId': typeof TemplatesSongIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/project/samples': typeof AppProjectSamplesRoute
  '/songs/$songId/play': typeof SongsSongIdPlayRoute
  '/_app/project/': typeof AppProjectIndexRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/sections/$sectionId': typeof SongsSongIdSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/explore'
    | '/profile'
    | '/project'
    | '/songs/$songId'
    | '/templates/$songId'
    | '/project/samples'
    | '/songs/$songId/play'
    | '/project/'
    | '/songs/$songId/'
    | '/songs/$songId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/explore'
    | '/profile'
    | '/templates/$songId'
    | '/'
    | '/project/samples'
    | '/songs/$songId/play'
    | '/project'
    | '/songs/$songId'
    | '/songs/$songId/sections/$sectionId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/explore'
    | '/_app/profile'
    | '/_app/project'
    | '/songs/$songId'
    | '/templates/$songId'
    | '/_app/'
    | '/_app/project/samples'
    | '/songs/$songId/play'
    | '/_app/project/'
    | '/songs/$songId/'
    | '/songs/$songId/sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SongsSongIdRoute: typeof SongsSongIdRouteWithChildren
  TemplatesSongIdRoute: typeof TemplatesSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/project': {
      id: '/_app/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof AppProjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$songId': {
      id: '/templates/$songId'
      path: '/templates/$songId'
      fullPath: '/templates/$songId'
      preLoaderRoute: typeof TemplatesSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/project/': {
      id: '/_app/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof AppProjectIndexRouteImport
      parentRoute: typeof AppProjectRoute
    }
    '/_app/project/samples': {
      id: '/_app/project/samples'
      path: '/samples'
      fullPath: '/project/samples'
      preLoaderRoute: typeof AppProjectSamplesRouteImport
      parentRoute: typeof AppProjectRoute
    }
    '/songs/$songId/': {
      id: '/songs/$songId/'
      path: '/'
      fullPath: '/songs/$songId/'
      preLoaderRoute: typeof SongsSongIdIndexRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
    '/songs/$songId/play': {
      id: '/songs/$songId/play'
      path: '/play'
      fullPath: '/songs/$songId/play'
      preLoaderRoute: typeof SongsSongIdPlayRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
    '/songs/$songId/sections/$sectionId': {
      id: '/songs/$songId/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/songs/$songId/sections/$sectionId'
      preLoaderRoute: typeof SongsSongIdSectionsSectionIdRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
  }
}

interface AppProjectRouteChildren {
  AppProjectSamplesRoute: typeof AppProjectSamplesRoute
  AppProjectIndexRoute: typeof AppProjectIndexRoute
}

const AppProjectRouteChildren: AppProjectRouteChildren = {
  AppProjectSamplesRoute: AppProjectSamplesRoute,
  AppProjectIndexRoute: AppProjectIndexRoute,
}

const AppProjectRouteWithChildren = AppProjectRoute._addFileChildren(
  AppProjectRouteChildren,
)

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectRoute: typeof AppProjectRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectRoute: AppProjectRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SongsSongIdRouteChildren {
  SongsSongIdPlayRoute: typeof SongsSongIdPlayRoute
  SongsSongIdIndexRoute: typeof SongsSongIdIndexRoute
  SongsSongIdSectionsSectionIdRoute: typeof SongsSongIdSectionsSectionIdRoute
}

const SongsSongIdRouteChildren: SongsSongIdRouteChildren = {
  SongsSongIdPlayRoute: SongsSongIdPlayRoute,
  SongsSongIdIndexRoute: SongsSongIdIndexRoute,
  SongsSongIdSectionsSectionIdRoute: SongsSongIdSectionsSectionIdRoute,
}

const SongsSongIdRouteWithChildren = SongsSongIdRoute._addFileChildren(
  SongsSongIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SongsSongIdRoute: SongsSongIdRouteWithChildren,
  TemplatesSongIdRoute: TemplatesSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
