/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSamplesRouteImport } from './routes/_authenticated/samples'
import { Route as AuthenticatedSongsRouteImport } from './routes/_authenticated/songs'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as TemplatesSongIdRouteImport } from './routes/templates.$songId'
import { Route as SongsSongIdIndexRouteImport } from './routes/songs.$songId.index'
import { Route as SongsSongIdPlayRouteImport } from './routes/songs.$songId.play'
import { Route as SongsSongIdSectionsSectionIdRouteImport } from './routes/songs.$songId.sections.$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesRoute = AuthenticatedSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSongsRoute = AuthenticatedSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSongIdRoute = TemplatesSongIdRouteImport.update({
  id: '/templates/$songId',
  path: '/templates/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdIndexRoute = SongsSongIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SongsSongIdRoute,
} as any)
const SongsSongIdPlayRoute = SongsSongIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => SongsSongIdRoute,
} as any)
const SongsSongIdSectionsSectionIdRoute =
  SongsSongIdSectionsSectionIdRouteImport.update({
    id: '/sections/$sectionId',
    path: '/sections/$sectionId',
    getParentRoute: () => SongsSongIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/samples': typeof AuthenticatedSamplesRoute
  '/songs': typeof AuthenticatedSongsRoute
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/templates/$songId': typeof TemplatesSongIdRoute
  '/songs/$songId/play': typeof SongsSongIdPlayRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/sections/$sectionId': typeof SongsSongIdSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/samples': typeof AuthenticatedSamplesRoute
  '/songs': typeof AuthenticatedSongsRoute
  '/templates/$songId': typeof TemplatesSongIdRoute
  '/songs/$songId/play': typeof SongsSongIdPlayRoute
  '/songs/$songId': typeof SongsSongIdIndexRoute
  '/songs/$songId/sections/$sectionId': typeof SongsSongIdSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/samples': typeof AuthenticatedSamplesRoute
  '/_authenticated/songs': typeof AuthenticatedSongsRoute
  '/songs/$songId': typeof SongsSongIdRouteWithChildren
  '/templates/$songId': typeof TemplatesSongIdRoute
  '/songs/$songId/play': typeof SongsSongIdPlayRoute
  '/songs/$songId/': typeof SongsSongIdIndexRoute
  '/songs/$songId/sections/$sectionId': typeof SongsSongIdSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/samples'
    | '/songs'
    | '/songs/$songId'
    | '/templates/$songId'
    | '/songs/$songId/play'
    | '/songs/$songId/'
    | '/songs/$songId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/samples'
    | '/songs'
    | '/templates/$songId'
    | '/songs/$songId/play'
    | '/songs/$songId'
    | '/songs/$songId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/samples'
    | '/_authenticated/songs'
    | '/songs/$songId'
    | '/templates/$songId'
    | '/songs/$songId/play'
    | '/songs/$songId/'
    | '/songs/$songId/sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SongsSongIdRoute: typeof SongsSongIdRouteWithChildren
  TemplatesSongIdRoute: typeof TemplatesSongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples': {
      id: '/_authenticated/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof AuthenticatedSamplesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/songs': {
      id: '/_authenticated/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof AuthenticatedSongsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$songId': {
      id: '/templates/$songId'
      path: '/templates/$songId'
      fullPath: '/templates/$songId'
      preLoaderRoute: typeof TemplatesSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId/': {
      id: '/songs/$songId/'
      path: '/'
      fullPath: '/songs/$songId/'
      preLoaderRoute: typeof SongsSongIdIndexRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
    '/songs/$songId/play': {
      id: '/songs/$songId/play'
      path: '/play'
      fullPath: '/songs/$songId/play'
      preLoaderRoute: typeof SongsSongIdPlayRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
    '/songs/$songId/sections/$sectionId': {
      id: '/songs/$songId/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/songs/$songId/sections/$sectionId'
      preLoaderRoute: typeof SongsSongIdSectionsSectionIdRouteImport
      parentRoute: typeof SongsSongIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSamplesRoute: typeof AuthenticatedSamplesRoute
  AuthenticatedSongsRoute: typeof AuthenticatedSongsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSamplesRoute: AuthenticatedSamplesRoute,
  AuthenticatedSongsRoute: AuthenticatedSongsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SongsSongIdRouteChildren {
  SongsSongIdPlayRoute: typeof SongsSongIdPlayRoute
  SongsSongIdIndexRoute: typeof SongsSongIdIndexRoute
  SongsSongIdSectionsSectionIdRoute: typeof SongsSongIdSectionsSectionIdRoute
}

const SongsSongIdRouteChildren: SongsSongIdRouteChildren = {
  SongsSongIdPlayRoute: SongsSongIdPlayRoute,
  SongsSongIdIndexRoute: SongsSongIdIndexRoute,
  SongsSongIdSectionsSectionIdRoute: SongsSongIdSectionsSectionIdRoute,
}

const SongsSongIdRouteWithChildren = SongsSongIdRoute._addFileChildren(
  SongsSongIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SongsSongIdRoute: SongsSongIdRouteWithChildren,
  TemplatesSongIdRoute: TemplatesSongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
