/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSongsRouteImport } from './routes/_authenticated/songs'
import { Route as AuthenticatedSamplesRouteImport } from './routes/_authenticated/samples'
import { Route as AuthenticatedSongsSongIdRouteImport } from './routes/_authenticated/songs/$songId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSongsRoute = AuthenticatedSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSamplesRoute = AuthenticatedSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSongsSongIdRoute =
  AuthenticatedSongsSongIdRouteImport.update({
    id: '/$songId',
    path: '/$songId',
    getParentRoute: () => AuthenticatedSongsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/samples': typeof AuthenticatedSamplesRoute
  '/songs': typeof AuthenticatedSongsRouteWithChildren
  '/songs/$songId': typeof AuthenticatedSongsSongIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/samples': typeof AuthenticatedSamplesRoute
  '/songs': typeof AuthenticatedSongsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/songs/$songId': typeof AuthenticatedSongsSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/samples': typeof AuthenticatedSamplesRoute
  '/_authenticated/songs': typeof AuthenticatedSongsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/songs/$songId': typeof AuthenticatedSongsSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/samples'
    | '/songs'
    | '/songs/$songId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/samples' | '/songs' | '/' | '/songs/$songId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/samples'
    | '/_authenticated/songs'
    | '/_authenticated/'
    | '/_authenticated/songs/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/songs': {
      id: '/_authenticated/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof AuthenticatedSongsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples': {
      id: '/_authenticated/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof AuthenticatedSamplesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/songs/$songId': {
      id: '/_authenticated/songs/$songId'
      path: '/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof AuthenticatedSongsSongIdRouteImport
      parentRoute: typeof AuthenticatedSongsRoute
    }
  }
}

interface AuthenticatedSongsRouteChildren {
  AuthenticatedSongsSongIdRoute: typeof AuthenticatedSongsSongIdRoute
}

const AuthenticatedSongsRouteChildren: AuthenticatedSongsRouteChildren = {
  AuthenticatedSongsSongIdRoute: AuthenticatedSongsSongIdRoute,
}

const AuthenticatedSongsRouteWithChildren =
  AuthenticatedSongsRoute._addFileChildren(AuthenticatedSongsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSamplesRoute: typeof AuthenticatedSamplesRoute
  AuthenticatedSongsRoute: typeof AuthenticatedSongsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSamplesRoute: AuthenticatedSamplesRoute,
  AuthenticatedSongsRoute: AuthenticatedSongsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
