/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoCreateSectionRequest,
  DtoErrorResponse,
  DtoReorderSectionRequest,
  DtoSuccessResponse,
  DtoUpdateSectionRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type putSectionsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSectionsIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSectionsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSectionsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSectionsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSectionsIdResponseSuccess = (putSectionsIdResponse200) & {
  headers: Headers;
};
export type putSectionsIdResponseError = (putSectionsIdResponse400 | putSectionsIdResponse401 | putSectionsIdResponse403 | putSectionsIdResponse404) & {
  headers: Headers;
};

export type putSectionsIdResponse = (putSectionsIdResponseSuccess | putSectionsIdResponseError)

export const getPutSectionsIdUrl = (id: number,) => {




  return `/sections/${id}`
}

/**
 * Update nama dan/atau bpm_override (null untuk kembali mengikuti BPM Song)
 * @summary Update section
 */
export const putSectionsId = async (id: number,
    dtoUpdateSectionRequest: DtoUpdateSectionRequest, options?: RequestInit): Promise<putSectionsIdResponse> => {

  return customInstance<putSectionsIdResponse>(getPutSectionsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoUpdateSectionRequest,)
  }
);}




export const getPutSectionsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSectionsId>>, TError,{id: number;data: DtoUpdateSectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSectionsId>>, TError,{id: number;data: DtoUpdateSectionRequest}, TContext> => {

const mutationKey = ['putSectionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSectionsId>>, {id: number;data: DtoUpdateSectionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSectionsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSectionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putSectionsId>>>
    export type PutSectionsIdMutationBody = DtoUpdateSectionRequest
    export type PutSectionsIdMutationError = DtoErrorResponse

    /**
 * @summary Update section
 */
export const usePutSectionsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSectionsId>>, TError,{id: number;data: DtoUpdateSectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSectionsId>>,
        TError,
        {id: number;data: DtoUpdateSectionRequest},
        TContext
      > => {
      return useMutation(getPutSectionsIdMutationOptions(options), queryClient);
    }
    export type deleteSectionsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteSectionsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteSectionsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type deleteSectionsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteSectionsIdResponseSuccess = (deleteSectionsIdResponse200) & {
  headers: Headers;
};
export type deleteSectionsIdResponseError = (deleteSectionsIdResponse401 | deleteSectionsIdResponse403 | deleteSectionsIdResponse404) & {
  headers: Headers;
};

export type deleteSectionsIdResponse = (deleteSectionsIdResponseSuccess | deleteSectionsIdResponseError)

export const getDeleteSectionsIdUrl = (id: number,) => {




  return `/sections/${id}`
}

/**
 * Hapus Section beserta seluruh SectionPart (cascade)
 * @summary Delete section
 */
export const deleteSectionsId = async (id: number, options?: RequestInit): Promise<deleteSectionsIdResponse> => {

  return customInstance<deleteSectionsIdResponse>(getDeleteSectionsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSectionsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSectionsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSectionsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteSectionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSectionsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteSectionsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSectionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSectionsId>>>

    export type DeleteSectionsIdMutationError = DtoErrorResponse

    /**
 * @summary Delete section
 */
export const useDeleteSectionsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSectionsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSectionsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteSectionsIdMutationOptions(options), queryClient);
    }
    export type postSectionsIdDuplicateResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postSectionsIdDuplicateResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postSectionsIdDuplicateResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type postSectionsIdDuplicateResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type postSectionsIdDuplicateResponseSuccess = (postSectionsIdDuplicateResponse201) & {
  headers: Headers;
};
export type postSectionsIdDuplicateResponseError = (postSectionsIdDuplicateResponse401 | postSectionsIdDuplicateResponse403 | postSectionsIdDuplicateResponse404) & {
  headers: Headers;
};

export type postSectionsIdDuplicateResponse = (postSectionsIdDuplicateResponseSuccess | postSectionsIdDuplicateResponseError)

export const getPostSectionsIdDuplicateUrl = (id: number,) => {




  return `/sections/${id}/duplicate`
}

/**
 * Duplikasi Section dalam Song yang sama (starting point variasi baru)
 * @summary Duplicate section
 */
export const postSectionsIdDuplicate = async (id: number, options?: RequestInit): Promise<postSectionsIdDuplicateResponse> => {

  return customInstance<postSectionsIdDuplicateResponse>(getPostSectionsIdDuplicateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostSectionsIdDuplicateMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSectionsIdDuplicate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postSectionsIdDuplicate>>, TError,{id: number}, TContext> => {

const mutationKey = ['postSectionsIdDuplicate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSectionsIdDuplicate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postSectionsIdDuplicate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSectionsIdDuplicateMutationResult = NonNullable<Awaited<ReturnType<typeof postSectionsIdDuplicate>>>

    export type PostSectionsIdDuplicateMutationError = DtoErrorResponse

    /**
 * @summary Duplicate section
 */
export const usePostSectionsIdDuplicate = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSectionsIdDuplicate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSectionsIdDuplicate>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostSectionsIdDuplicateMutationOptions(options), queryClient);
    }
    export type putSectionsIdReorderResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSectionsIdReorderResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSectionsIdReorderResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSectionsIdReorderResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSectionsIdReorderResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSectionsIdReorderResponseSuccess = (putSectionsIdReorderResponse200) & {
  headers: Headers;
};
export type putSectionsIdReorderResponseError = (putSectionsIdReorderResponse400 | putSectionsIdReorderResponse401 | putSectionsIdReorderResponse403 | putSectionsIdReorderResponse404) & {
  headers: Headers;
};

export type putSectionsIdReorderResponse = (putSectionsIdReorderResponseSuccess | putSectionsIdReorderResponseError)

export const getPutSectionsIdReorderUrl = (id: number,) => {




  return `/sections/${id}/reorder`
}

/**
 * Pindahkan Section ke posisi baru; seluruh order_index dinormalkan ulang
 * @summary Reorder section
 */
export const putSectionsIdReorder = async (id: number,
    dtoReorderSectionRequest: DtoReorderSectionRequest, options?: RequestInit): Promise<putSectionsIdReorderResponse> => {

  return customInstance<putSectionsIdReorderResponse>(getPutSectionsIdReorderUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoReorderSectionRequest,)
  }
);}




export const getPutSectionsIdReorderMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSectionsIdReorder>>, TError,{id: number;data: DtoReorderSectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSectionsIdReorder>>, TError,{id: number;data: DtoReorderSectionRequest}, TContext> => {

const mutationKey = ['putSectionsIdReorder'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSectionsIdReorder>>, {id: number;data: DtoReorderSectionRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSectionsIdReorder(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSectionsIdReorderMutationResult = NonNullable<Awaited<ReturnType<typeof putSectionsIdReorder>>>
    export type PutSectionsIdReorderMutationBody = DtoReorderSectionRequest
    export type PutSectionsIdReorderMutationError = DtoErrorResponse

    /**
 * @summary Reorder section
 */
export const usePutSectionsIdReorder = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSectionsIdReorder>>, TError,{id: number;data: DtoReorderSectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSectionsIdReorder>>,
        TError,
        {id: number;data: DtoReorderSectionRequest},
        TContext
      > => {
      return useMutation(getPutSectionsIdReorderMutationOptions(options), queryClient);
    }
    export type postSongsSongIdSectionsResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postSongsSongIdSectionsResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postSongsSongIdSectionsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postSongsSongIdSectionsResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type postSongsSongIdSectionsResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type postSongsSongIdSectionsResponseSuccess = (postSongsSongIdSectionsResponse201) & {
  headers: Headers;
};
export type postSongsSongIdSectionsResponseError = (postSongsSongIdSectionsResponse400 | postSongsSongIdSectionsResponse401 | postSongsSongIdSectionsResponse403 | postSongsSongIdSectionsResponse404) & {
  headers: Headers;
};

export type postSongsSongIdSectionsResponse = (postSongsSongIdSectionsResponseSuccess | postSongsSongIdSectionsResponseError)

export const getPostSongsSongIdSectionsUrl = (songId: number,) => {




  return `/songs/${songId}/sections`
}

/**
 * Tambah Section baru (nama bebas) — otomatis dibuat 5 SectionPart (satu per Part)
 * @summary Create section
 */
export const postSongsSongIdSections = async (songId: number,
    dtoCreateSectionRequest: DtoCreateSectionRequest, options?: RequestInit): Promise<postSongsSongIdSectionsResponse> => {

  return customInstance<postSongsSongIdSectionsResponse>(getPostSongsSongIdSectionsUrl(songId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateSectionRequest,)
  }
);}




export const getPostSongsSongIdSectionsMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSongsSongIdSections>>, TError,{songId: number;data: DtoCreateSectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postSongsSongIdSections>>, TError,{songId: number;data: DtoCreateSectionRequest}, TContext> => {

const mutationKey = ['postSongsSongIdSections'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSongsSongIdSections>>, {songId: number;data: DtoCreateSectionRequest}> = (props) => {
          const {songId,data} = props ?? {};

          return  postSongsSongIdSections(songId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSongsSongIdSectionsMutationResult = NonNullable<Awaited<ReturnType<typeof postSongsSongIdSections>>>
    export type PostSongsSongIdSectionsMutationBody = DtoCreateSectionRequest
    export type PostSongsSongIdSectionsMutationError = DtoErrorResponse

    /**
 * @summary Create section
 */
export const usePostSongsSongIdSections = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSongsSongIdSections>>, TError,{songId: number;data: DtoCreateSectionRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSongsSongIdSections>>,
        TError,
        {songId: number;data: DtoCreateSectionRequest},
        TContext
      > => {
      return useMutation(getPostSongsSongIdSectionsMutationOptions(options), queryClient);
    }
