/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoErrorResponse,
  DtoSuccessResponse,
  DtoUpdateStepsRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type putSectionPartsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSectionPartsIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSectionPartsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSectionPartsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSectionPartsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSectionPartsIdResponseSuccess = (putSectionPartsIdResponse200) & {
  headers: Headers;
};
export type putSectionPartsIdResponseError = (putSectionPartsIdResponse400 | putSectionPartsIdResponse401 | putSectionPartsIdResponse403 | putSectionPartsIdResponse404) & {
  headers: Headers;
};

export type putSectionPartsIdResponse = (putSectionPartsIdResponseSuccess | putSectionPartsIdResponseError)

export const getPutSectionPartsIdUrl = (id: number,) => {




  return `/section-parts/${id}`
}

/**
 * Update rumus pukulan (steps) — tiap karakter harus merujuk key SoundSlot pada SectionPart terkait
 * @summary Update section part steps
 */
export const putSectionPartsId = async (id: number,
    dtoUpdateStepsRequest: DtoUpdateStepsRequest, options?: RequestInit): Promise<putSectionPartsIdResponse> => {

  return customInstance<putSectionPartsIdResponse>(getPutSectionPartsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoUpdateStepsRequest,)
  }
);}




export const getPutSectionPartsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSectionPartsId>>, TError,{id: number;data: DtoUpdateStepsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSectionPartsId>>, TError,{id: number;data: DtoUpdateStepsRequest}, TContext> => {

const mutationKey = ['putSectionPartsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSectionPartsId>>, {id: number;data: DtoUpdateStepsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSectionPartsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSectionPartsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putSectionPartsId>>>
    export type PutSectionPartsIdMutationBody = DtoUpdateStepsRequest
    export type PutSectionPartsIdMutationError = DtoErrorResponse

    /**
 * @summary Update section part steps
 */
export const usePutSectionPartsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSectionPartsId>>, TError,{id: number;data: DtoUpdateStepsRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSectionPartsId>>,
        TError,
        {id: number;data: DtoUpdateStepsRequest},
        TContext
      > => {
      return useMutation(getPutSectionPartsIdMutationOptions(options), queryClient);
    }
    export type getSectionsIdPartsResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSectionsIdPartsResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type getSectionsIdPartsResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getSectionsIdPartsResponseSuccess = (getSectionsIdPartsResponse200) & {
  headers: Headers;
};
export type getSectionsIdPartsResponseError = (getSectionsIdPartsResponse403 | getSectionsIdPartsResponse404) & {
  headers: Headers;
};

export type getSectionsIdPartsResponse = (getSectionsIdPartsResponseSuccess | getSectionsIdPartsResponseError)

export const getGetSectionsIdPartsUrl = (id: number,) => {




  return `/sections/${id}/parts`
}

/**
 * Daftar 5 SectionPart milik Section beserta SoundSlots (nested). Section Song Template dapat dilihat Guest.
 * @summary List section parts
 */
export const getSectionsIdParts = async (id: number, options?: RequestInit): Promise<getSectionsIdPartsResponse> => {

  return customInstance<getSectionsIdPartsResponse>(getGetSectionsIdPartsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSectionsIdPartsQueryKey = (id: number,) => {
    return [
    `/sections/${id}/parts`
    ] as const;
    }


export const getGetSectionsIdPartsQueryOptions = <TData = Awaited<ReturnType<typeof getSectionsIdParts>>, TError = DtoErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionsIdParts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSectionsIdPartsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSectionsIdParts>>> = ({ signal }) => getSectionsIdParts(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSectionsIdParts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSectionsIdPartsQueryResult = NonNullable<Awaited<ReturnType<typeof getSectionsIdParts>>>
export type GetSectionsIdPartsQueryError = DtoErrorResponse


export function useGetSectionsIdParts<TData = Awaited<ReturnType<typeof getSectionsIdParts>>, TError = DtoErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionsIdParts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSectionsIdParts>>,
          TError,
          Awaited<ReturnType<typeof getSectionsIdParts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSectionsIdParts<TData = Awaited<ReturnType<typeof getSectionsIdParts>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionsIdParts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSectionsIdParts>>,
          TError,
          Awaited<ReturnType<typeof getSectionsIdParts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSectionsIdParts<TData = Awaited<ReturnType<typeof getSectionsIdParts>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionsIdParts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List section parts
 */

export function useGetSectionsIdParts<TData = Awaited<ReturnType<typeof getSectionsIdParts>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionsIdParts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSectionsIdPartsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






