/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoCreateSongRequest,
  DtoErrorResponse,
  DtoSuccessResponse,
  DtoUpdateSongRequest,
  DtoUpdateSongVisibilityRequest
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getSongsResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSongsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getSongsResponseSuccess = (getSongsResponse200) & {
  headers: Headers;
};
export type getSongsResponseError = (getSongsResponse401) & {
  headers: Headers;
};

export type getSongsResponse = (getSongsResponseSuccess | getSongsResponseError)

export const getGetSongsUrl = () => {




  return `/songs`
}

/**
 * Daftar Song milik user yang sedang login
 * @summary List user songs
 */
export const getSongs = async ( options?: RequestInit): Promise<getSongsResponse> => {

  return customInstance<getSongsResponse>(getGetSongsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSongsQueryKey = () => {
    return [
    `/songs`
    ] as const;
    }


export const getGetSongsQueryOptions = <TData = Awaited<ReturnType<typeof getSongs>>, TError = DtoErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSongsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSongs>>> = ({ signal }) => getSongs({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSongs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSongsQueryResult = NonNullable<Awaited<ReturnType<typeof getSongs>>>
export type GetSongsQueryError = DtoErrorResponse


export function useGetSongs<TData = Awaited<ReturnType<typeof getSongs>>, TError = DtoErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongs>>,
          TError,
          Awaited<ReturnType<typeof getSongs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongs<TData = Awaited<ReturnType<typeof getSongs>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongs>>,
          TError,
          Awaited<ReturnType<typeof getSongs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongs<TData = Awaited<ReturnType<typeof getSongs>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List user songs
 */

export function useGetSongs<TData = Awaited<ReturnType<typeof getSongs>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSongsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postSongsResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postSongsResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postSongsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postSongsResponseSuccess = (postSongsResponse201) & {
  headers: Headers;
};
export type postSongsResponseError = (postSongsResponse400 | postSongsResponse401) & {
  headers: Headers;
};

export type postSongsResponse = (postSongsResponseSuccess | postSongsResponseError)

export const getPostSongsUrl = () => {




  return `/songs`
}

/**
 * Buat Song baru (nama, BPM) milik user yang login
 * @summary Create song
 */
export const postSongs = async (dtoCreateSongRequest: DtoCreateSongRequest, options?: RequestInit): Promise<postSongsResponse> => {

  return customInstance<postSongsResponse>(getPostSongsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateSongRequest,)
  }
);}




export const getPostSongsMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSongs>>, TError,{data: DtoCreateSongRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postSongs>>, TError,{data: DtoCreateSongRequest}, TContext> => {

const mutationKey = ['postSongs'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSongs>>, {data: DtoCreateSongRequest}> = (props) => {
          const {data} = props ?? {};

          return  postSongs(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSongsMutationResult = NonNullable<Awaited<ReturnType<typeof postSongs>>>
    export type PostSongsMutationBody = DtoCreateSongRequest
    export type PostSongsMutationError = DtoErrorResponse

    /**
 * @summary Create song
 */
export const usePostSongs = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSongs>>, TError,{data: DtoCreateSongRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSongs>>,
        TError,
        {data: DtoCreateSongRequest},
        TContext
      > => {
      return useMutation(getPostSongsMutationOptions(options), queryClient);
    }
    export type getSongsPublicResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSongsPublicResponseSuccess = (getSongsPublicResponse200) & {
  headers: Headers;
};
;

export type getSongsPublicResponse = (getSongsPublicResponseSuccess)

export const getGetSongsPublicUrl = () => {




  return `/songs/public`
}

/**
 * Daftar lagu publik milik user (dengan author_name) untuk Explore — Guest maupun User login
 * @summary List public songs
 */
export const getSongsPublic = async ( options?: RequestInit): Promise<getSongsPublicResponse> => {

  return customInstance<getSongsPublicResponse>(getGetSongsPublicUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSongsPublicQueryKey = () => {
    return [
    `/songs/public`
    ] as const;
    }


export const getGetSongsPublicQueryOptions = <TData = Awaited<ReturnType<typeof getSongsPublic>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsPublic>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSongsPublicQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSongsPublic>>> = ({ signal }) => getSongsPublic({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSongsPublic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSongsPublicQueryResult = NonNullable<Awaited<ReturnType<typeof getSongsPublic>>>
export type GetSongsPublicQueryError = unknown


export function useGetSongsPublic<TData = Awaited<ReturnType<typeof getSongsPublic>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsPublic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongsPublic>>,
          TError,
          Awaited<ReturnType<typeof getSongsPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongsPublic<TData = Awaited<ReturnType<typeof getSongsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsPublic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongsPublic>>,
          TError,
          Awaited<ReturnType<typeof getSongsPublic>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongsPublic<TData = Awaited<ReturnType<typeof getSongsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsPublic>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List public songs
 */

export function useGetSongsPublic<TData = Awaited<ReturnType<typeof getSongsPublic>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsPublic>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSongsPublicQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getSongsTemplatesResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSongsTemplatesResponseSuccess = (getSongsTemplatesResponse200) & {
  headers: Headers;
};
;

export type getSongsTemplatesResponse = (getSongsTemplatesResponseSuccess)

export const getGetSongsTemplatesUrl = () => {




  return `/songs/templates`
}

/**
 * Daftar Song Template System — dapat diakses Guest maupun User login
 * @summary List song templates
 */
export const getSongsTemplates = async ( options?: RequestInit): Promise<getSongsTemplatesResponse> => {

  return customInstance<getSongsTemplatesResponse>(getGetSongsTemplatesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSongsTemplatesQueryKey = () => {
    return [
    `/songs/templates`
    ] as const;
    }


export const getGetSongsTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getSongsTemplates>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSongsTemplatesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSongsTemplates>>> = ({ signal }) => getSongsTemplates({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSongsTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSongsTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getSongsTemplates>>>
export type GetSongsTemplatesQueryError = unknown


export function useGetSongsTemplates<TData = Awaited<ReturnType<typeof getSongsTemplates>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getSongsTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongsTemplates<TData = Awaited<ReturnType<typeof getSongsTemplates>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getSongsTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongsTemplates<TData = Awaited<ReturnType<typeof getSongsTemplates>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List song templates
 */

export function useGetSongsTemplates<TData = Awaited<ReturnType<typeof getSongsTemplates>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSongsTemplatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getSongsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getSongsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type getSongsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getSongsIdResponseSuccess = (getSongsIdResponse200) & {
  headers: Headers;
};
export type getSongsIdResponseError = (getSongsIdResponse403 | getSongsIdResponse404) & {
  headers: Headers;
};

export type getSongsIdResponse = (getSongsIdResponseSuccess | getSongsIdResponseError)

export const getGetSongsIdUrl = (id: number,) => {




  return `/songs/${id}`
}

/**
 * Detail Song. Song Template System dapat diakses Guest; Song milik User hanya pemiliknya.
 * @summary Get song by id
 */
export const getSongsId = async (id: number, options?: RequestInit): Promise<getSongsIdResponse> => {

  return customInstance<getSongsIdResponse>(getGetSongsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSongsIdQueryKey = (id: number,) => {
    return [
    `/songs/${id}`
    ] as const;
    }


export const getGetSongsIdQueryOptions = <TData = Awaited<ReturnType<typeof getSongsId>>, TError = DtoErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSongsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSongsId>>> = ({ signal }) => getSongsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSongsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSongsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSongsId>>>
export type GetSongsIdQueryError = DtoErrorResponse


export function useGetSongsId<TData = Awaited<ReturnType<typeof getSongsId>>, TError = DtoErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongsId>>,
          TError,
          Awaited<ReturnType<typeof getSongsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongsId<TData = Awaited<ReturnType<typeof getSongsId>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSongsId>>,
          TError,
          Awaited<ReturnType<typeof getSongsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSongsId<TData = Awaited<ReturnType<typeof getSongsId>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get song by id
 */

export function useGetSongsId<TData = Awaited<ReturnType<typeof getSongsId>>, TError = DtoErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSongsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSongsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type putSongsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSongsIdResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSongsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSongsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSongsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSongsIdResponseSuccess = (putSongsIdResponse200) & {
  headers: Headers;
};
export type putSongsIdResponseError = (putSongsIdResponse400 | putSongsIdResponse401 | putSongsIdResponse403 | putSongsIdResponse404) & {
  headers: Headers;
};

export type putSongsIdResponse = (putSongsIdResponseSuccess | putSongsIdResponseError)

export const getPutSongsIdUrl = (id: number,) => {




  return `/songs/${id}`
}

/**
 * Update nama/BPM Song milik user. Ditolak 403 untuk Song Template System.
 * @summary Update song
 */
export const putSongsId = async (id: number,
    dtoUpdateSongRequest: DtoUpdateSongRequest, options?: RequestInit): Promise<putSongsIdResponse> => {

  return customInstance<putSongsIdResponse>(getPutSongsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoUpdateSongRequest,)
  }
);}




export const getPutSongsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSongsId>>, TError,{id: number;data: DtoUpdateSongRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSongsId>>, TError,{id: number;data: DtoUpdateSongRequest}, TContext> => {

const mutationKey = ['putSongsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSongsId>>, {id: number;data: DtoUpdateSongRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSongsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSongsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putSongsId>>>
    export type PutSongsIdMutationBody = DtoUpdateSongRequest
    export type PutSongsIdMutationError = DtoErrorResponse

    /**
 * @summary Update song
 */
export const usePutSongsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSongsId>>, TError,{id: number;data: DtoUpdateSongRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSongsId>>,
        TError,
        {id: number;data: DtoUpdateSongRequest},
        TContext
      > => {
      return useMutation(getPutSongsIdMutationOptions(options), queryClient);
    }
    export type deleteSongsIdResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteSongsIdResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteSongsIdResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type deleteSongsIdResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type deleteSongsIdResponseSuccess = (deleteSongsIdResponse200) & {
  headers: Headers;
};
export type deleteSongsIdResponseError = (deleteSongsIdResponse401 | deleteSongsIdResponse403 | deleteSongsIdResponse404) & {
  headers: Headers;
};

export type deleteSongsIdResponse = (deleteSongsIdResponseSuccess | deleteSongsIdResponseError)

export const getDeleteSongsIdUrl = (id: number,) => {




  return `/songs/${id}`
}

/**
 * Hapus Song beserta seluruh Section (cascade). Ditolak 403 untuk Song Template System.
 * @summary Delete song
 */
export const deleteSongsId = async (id: number, options?: RequestInit): Promise<deleteSongsIdResponse> => {

  return customInstance<deleteSongsIdResponse>(getDeleteSongsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSongsIdMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSongsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSongsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteSongsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSongsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteSongsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSongsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSongsId>>>

    export type DeleteSongsIdMutationError = DtoErrorResponse

    /**
 * @summary Delete song
 */
export const useDeleteSongsId = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSongsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSongsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteSongsIdMutationOptions(options), queryClient);
    }
    export type postSongsIdDuplicateResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postSongsIdDuplicateResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postSongsIdDuplicateResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type postSongsIdDuplicateResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type postSongsIdDuplicateResponseSuccess = (postSongsIdDuplicateResponse201) & {
  headers: Headers;
};
export type postSongsIdDuplicateResponseError = (postSongsIdDuplicateResponse401 | postSongsIdDuplicateResponse403 | postSongsIdDuplicateResponse404) & {
  headers: Headers;
};

export type postSongsIdDuplicateResponse = (postSongsIdDuplicateResponseSuccess | postSongsIdDuplicateResponseError)

export const getPostSongsIdDuplicateUrl = (id: number,) => {




  return `/songs/${id}/duplicate`
}

/**
 * Duplikasi Song (deep copy Section/SectionPart/SoundSlot). Hasil milik user login.
 * @summary Duplicate song
 */
export const postSongsIdDuplicate = async (id: number, options?: RequestInit): Promise<postSongsIdDuplicateResponse> => {

  return customInstance<postSongsIdDuplicateResponse>(getPostSongsIdDuplicateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostSongsIdDuplicateMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSongsIdDuplicate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postSongsIdDuplicate>>, TError,{id: number}, TContext> => {

const mutationKey = ['postSongsIdDuplicate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSongsIdDuplicate>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postSongsIdDuplicate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSongsIdDuplicateMutationResult = NonNullable<Awaited<ReturnType<typeof postSongsIdDuplicate>>>

    export type PostSongsIdDuplicateMutationError = DtoErrorResponse

    /**
 * @summary Duplicate song
 */
export const usePostSongsIdDuplicate = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSongsIdDuplicate>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSongsIdDuplicate>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostSongsIdDuplicateMutationOptions(options), queryClient);
    }
    export type putSongsIdVisibilityResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type putSongsIdVisibilityResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type putSongsIdVisibilityResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type putSongsIdVisibilityResponse403 = {
  data: DtoErrorResponse
  status: 403
}

export type putSongsIdVisibilityResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type putSongsIdVisibilityResponseSuccess = (putSongsIdVisibilityResponse200) & {
  headers: Headers;
};
export type putSongsIdVisibilityResponseError = (putSongsIdVisibilityResponse400 | putSongsIdVisibilityResponse401 | putSongsIdVisibilityResponse403 | putSongsIdVisibilityResponse404) & {
  headers: Headers;
};

export type putSongsIdVisibilityResponse = (putSongsIdVisibilityResponseSuccess | putSongsIdVisibilityResponseError)

export const getPutSongsIdVisibilityUrl = (id: number,) => {




  return `/songs/${id}/visibility`
}

/**
 * Ubah status lagu public/private. Hanya admin pemilik lagu (FR-VIS); lagu template tidak bisa diubah statusnya.
 * @summary Update song visibility (public/private)
 */
export const putSongsIdVisibility = async (id: number,
    dtoUpdateSongVisibilityRequest: DtoUpdateSongVisibilityRequest, options?: RequestInit): Promise<putSongsIdVisibilityResponse> => {

  return customInstance<putSongsIdVisibilityResponse>(getPutSongsIdVisibilityUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoUpdateSongVisibilityRequest,)
  }
);}




export const getPutSongsIdVisibilityMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSongsIdVisibility>>, TError,{id: number;data: DtoUpdateSongVisibilityRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putSongsIdVisibility>>, TError,{id: number;data: DtoUpdateSongVisibilityRequest}, TContext> => {

const mutationKey = ['putSongsIdVisibility'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putSongsIdVisibility>>, {id: number;data: DtoUpdateSongVisibilityRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putSongsIdVisibility(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutSongsIdVisibilityMutationResult = NonNullable<Awaited<ReturnType<typeof putSongsIdVisibility>>>
    export type PutSongsIdVisibilityMutationBody = DtoUpdateSongVisibilityRequest
    export type PutSongsIdVisibilityMutationError = DtoErrorResponse

    /**
 * @summary Update song visibility (public/private)
 */
export const usePutSongsIdVisibility = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putSongsIdVisibility>>, TError,{id: number;data: DtoUpdateSongVisibilityRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putSongsIdVisibility>>,
        TError,
        {id: number;data: DtoUpdateSongVisibilityRequest},
        TContext
      > => {
      return useMutation(getPutSongsIdVisibilityMutationOptions(options), queryClient);
    }
