/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * BandJari API
 * API untuk BandJari — penyusun & pemutar pola pukulan rebana Al-Banjari.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoChangePasswordRequest,
  DtoCheckEmailRequest,
  DtoCheckEmailResponse,
  DtoCreateUserRequest,
  DtoDeleteAccountRequest,
  DtoErrorResponse,
  DtoForgotPasswordRequest,
  DtoLoginUserRequest,
  DtoLoginUserResponse,
  DtoRefreshTokenResponse,
  DtoResendVerificationRequest,
  DtoResetPasswordRequest,
  DtoSetPasswordRequest,
  DtoSuccessResponse,
  DtoUpdateUserRequest,
  DtoVerifyEmailRequest,
  GetAuthGoogleParams
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postAuthChangePasswordResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthChangePasswordResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthChangePasswordResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postAuthChangePasswordResponseSuccess = (postAuthChangePasswordResponse200) & {
  headers: Headers;
};
export type postAuthChangePasswordResponseError = (postAuthChangePasswordResponse400 | postAuthChangePasswordResponse401) & {
  headers: Headers;
};

export type postAuthChangePasswordResponse = (postAuthChangePasswordResponseSuccess | postAuthChangePasswordResponseError)

export const getPostAuthChangePasswordUrl = () => {




  return `/auth/change-password`
}

/**
 * Ganti password dengan verifikasi password lama; semua sesi lain dicabut
 * @summary Change password
 */
export const postAuthChangePassword = async (dtoChangePasswordRequest: DtoChangePasswordRequest, options?: RequestInit): Promise<postAuthChangePasswordResponse> => {

  return customInstance<postAuthChangePasswordResponse>(getPostAuthChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoChangePasswordRequest,)
  }
);}




export const getPostAuthChangePasswordMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,{data: DtoChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,{data: DtoChangePasswordRequest}, TContext> => {

const mutationKey = ['postAuthChangePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthChangePassword>>, {data: DtoChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthChangePassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthChangePassword>>>
    export type PostAuthChangePasswordMutationBody = DtoChangePasswordRequest
    export type PostAuthChangePasswordMutationError = DtoErrorResponse

    /**
 * @summary Change password
 */
export const usePostAuthChangePassword = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,{data: DtoChangePasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthChangePassword>>,
        TError,
        {data: DtoChangePasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthChangePasswordMutationOptions(options), queryClient);
    }
    export type postAuthCheckEmailResponse200 = {
  data: DtoCheckEmailResponse
  status: 200
}

export type postAuthCheckEmailResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthCheckEmailResponseSuccess = (postAuthCheckEmailResponse200) & {
  headers: Headers;
};
export type postAuthCheckEmailResponseError = (postAuthCheckEmailResponse400) & {
  headers: Headers;
};

export type postAuthCheckEmailResponse = (postAuthCheckEmailResponseSuccess | postAuthCheckEmailResponseError)

export const getPostAuthCheckEmailUrl = () => {




  return `/auth/check-email`
}

/**
 * Email-first login: kembalikan metode login (password/google/none)
 * @summary Check login method for email
 */
export const postAuthCheckEmail = async (dtoCheckEmailRequest: DtoCheckEmailRequest, options?: RequestInit): Promise<postAuthCheckEmailResponse> => {

  return customInstance<postAuthCheckEmailResponse>(getPostAuthCheckEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCheckEmailRequest,)
  }
);}




export const getPostAuthCheckEmailMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthCheckEmail>>, TError,{data: DtoCheckEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthCheckEmail>>, TError,{data: DtoCheckEmailRequest}, TContext> => {

const mutationKey = ['postAuthCheckEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthCheckEmail>>, {data: DtoCheckEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthCheckEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthCheckEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthCheckEmail>>>
    export type PostAuthCheckEmailMutationBody = DtoCheckEmailRequest
    export type PostAuthCheckEmailMutationError = DtoErrorResponse

    /**
 * @summary Check login method for email
 */
export const usePostAuthCheckEmail = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthCheckEmail>>, TError,{data: DtoCheckEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthCheckEmail>>,
        TError,
        {data: DtoCheckEmailRequest},
        TContext
      > => {
      return useMutation(getPostAuthCheckEmailMutationOptions(options), queryClient);
    }
    export type postAuthDeleteAccountResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthDeleteAccountResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthDeleteAccountResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postAuthDeleteAccountResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type postAuthDeleteAccountResponseSuccess = (postAuthDeleteAccountResponse200) & {
  headers: Headers;
};
export type postAuthDeleteAccountResponseError = (postAuthDeleteAccountResponse400 | postAuthDeleteAccountResponse401 | postAuthDeleteAccountResponse404) & {
  headers: Headers;
};

export type postAuthDeleteAccountResponse = (postAuthDeleteAccountResponseSuccess | postAuthDeleteAccountResponseError)

export const getPostAuthDeleteAccountUrl = () => {




  return `/auth/delete-account`
}

/**
 * Hapus akun: soft delete + anonimisasi email + revoke semua sesi.
Password wajib untuk akun ber-password; Google-only cukup sesi aktif.
 * @summary Delete account
 */
export const postAuthDeleteAccount = async (dtoDeleteAccountRequest: DtoDeleteAccountRequest, options?: RequestInit): Promise<postAuthDeleteAccountResponse> => {

  return customInstance<postAuthDeleteAccountResponse>(getPostAuthDeleteAccountUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoDeleteAccountRequest,)
  }
);}




export const getPostAuthDeleteAccountMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthDeleteAccount>>, TError,{data: DtoDeleteAccountRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthDeleteAccount>>, TError,{data: DtoDeleteAccountRequest}, TContext> => {

const mutationKey = ['postAuthDeleteAccount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthDeleteAccount>>, {data: DtoDeleteAccountRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthDeleteAccount(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthDeleteAccountMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthDeleteAccount>>>
    export type PostAuthDeleteAccountMutationBody = DtoDeleteAccountRequest
    export type PostAuthDeleteAccountMutationError = DtoErrorResponse

    /**
 * @summary Delete account
 */
export const usePostAuthDeleteAccount = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthDeleteAccount>>, TError,{data: DtoDeleteAccountRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthDeleteAccount>>,
        TError,
        {data: DtoDeleteAccountRequest},
        TContext
      > => {
      return useMutation(getPostAuthDeleteAccountMutationOptions(options), queryClient);
    }
    export type postAuthForgotPasswordResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthForgotPasswordResponseSuccess = (postAuthForgotPasswordResponse200) & {
  headers: Headers;
};
;

export type postAuthForgotPasswordResponse = (postAuthForgotPasswordResponseSuccess)

export const getPostAuthForgotPasswordUrl = () => {




  return `/auth/forgot-password`
}

/**
 * Kirim link reset password. Respons selalu 200 (anti email-enumeration)
 * @summary Request password reset
 */
export const postAuthForgotPassword = async (dtoForgotPasswordRequest: DtoForgotPasswordRequest, options?: RequestInit): Promise<postAuthForgotPasswordResponse> => {

  return customInstance<postAuthForgotPasswordResponse>(getPostAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoForgotPasswordRequest,)
  }
);}




export const getPostAuthForgotPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,{data: DtoForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,{data: DtoForgotPasswordRequest}, TContext> => {

const mutationKey = ['postAuthForgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthForgotPassword>>, {data: DtoForgotPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthForgotPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthForgotPassword>>>
    export type PostAuthForgotPasswordMutationBody = DtoForgotPasswordRequest
    export type PostAuthForgotPasswordMutationError = unknown

    /**
 * @summary Request password reset
 */
export const usePostAuthForgotPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,{data: DtoForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthForgotPassword>>,
        TError,
        {data: DtoForgotPasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthForgotPasswordMutationOptions(options), queryClient);
    }
    export type getAuthGoogleResponse302 = {
  data: void
  status: 302
}

;
export type getAuthGoogleResponseError = (getAuthGoogleResponse302) & {
  headers: Headers;
};

export type getAuthGoogleResponse = (getAuthGoogleResponseError)

export const getGetAuthGoogleUrl = (params?: GetAuthGoogleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/google?${stringifiedParams}` : `/auth/google`
}

/**
 * Redirect ke Google OAuth (state di cookie, anti-CSRF).
Param `link=1` menandakan mode LINK (hubungkan Google ke akun
yang sedang login) — dipakai dari halaman Profile.
 * @summary Login with Google
 */
export const getAuthGoogle = async (params?: GetAuthGoogleParams, options?: RequestInit): Promise<getAuthGoogleResponse> => {

  return customInstance<getAuthGoogleResponse>(getGetAuthGoogleUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthGoogleQueryKey = (params?: GetAuthGoogleParams,) => {
    return [
    `/auth/google`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthGoogleQueryOptions = <TData = Awaited<ReturnType<typeof getAuthGoogle>>, TError = void>(params?: GetAuthGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthGoogleQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthGoogle>>> = ({ signal }) => getAuthGoogle(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthGoogleQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthGoogle>>>
export type GetAuthGoogleQueryError = void


export function useGetAuthGoogle<TData = Awaited<ReturnType<typeof getAuthGoogle>>, TError = void>(
 params: undefined |  GetAuthGoogleParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogle>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthGoogle<TData = Awaited<ReturnType<typeof getAuthGoogle>>, TError = void>(
 params?: GetAuthGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogle>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthGoogle<TData = Awaited<ReturnType<typeof getAuthGoogle>>, TError = void>(
 params?: GetAuthGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Login with Google
 */

export function useGetAuthGoogle<TData = Awaited<ReturnType<typeof getAuthGoogle>>, TError = void>(
 params?: GetAuthGoogleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogle>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthGoogleQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getAuthGoogleCallbackResponse302 = {
  data: void
  status: 302
}

;
export type getAuthGoogleCallbackResponseError = (getAuthGoogleCallbackResponse302) & {
  headers: Headers;
};

export type getAuthGoogleCallbackResponse = (getAuthGoogleCallbackResponseError)

export const getGetAuthGoogleCallbackUrl = () => {




  return `/auth/google/callback`
}

/**
 * Tukar code → profil → buat/link akun → set session → redirect ke frontend.
Mode link (state diawali "link:") → hubungkan provider ke user
sesi aktif (validasi refresh cookie) → redirect /profile.
 * @summary Google OAuth callback
 */
export const getAuthGoogleCallback = async ( options?: RequestInit): Promise<getAuthGoogleCallbackResponse> => {

  return customInstance<getAuthGoogleCallbackResponse>(getGetAuthGoogleCallbackUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthGoogleCallbackQueryKey = () => {
    return [
    `/auth/google/callback`
    ] as const;
    }


export const getGetAuthGoogleCallbackQueryOptions = <TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthGoogleCallbackQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthGoogleCallback>>> = ({ signal }) => getAuthGoogleCallback({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthGoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthGoogleCallback>>>
export type GetAuthGoogleCallbackQueryError = void


export function useGetAuthGoogleCallback<TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthGoogleCallback<TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleCallback>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthGoogleCallback<TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Google OAuth callback
 */

export function useGetAuthGoogleCallback<TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthGoogleCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postAuthLoginResponse200 = {
  data: DtoLoginUserResponse
  status: 200
}

export type postAuthLoginResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthLoginResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse400 | postAuthLoginResponse401) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {




  return `/auth/login`
}

/**
 * Authenticate user and return JWT token
 * @summary Login user
 */
export const postAuthLogin = async (dtoLoginUserRequest: DtoLoginUserRequest, options?: RequestInit): Promise<postAuthLoginResponse> => {

  return customInstance<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoLoginUserRequest,)
  }
);}




export const getPostAuthLoginMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtoLoginUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtoLoginUserRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: DtoLoginUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = DtoLoginUserRequest
    export type PostAuthLoginMutationError = DtoErrorResponse

    /**
 * @summary Login user
 */
export const usePostAuthLogin = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: DtoLoginUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: DtoLoginUserRequest},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }
    export type postAuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse204) & {
  headers: Headers;
};
;

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess)

export const getPostAuthLogoutUrl = () => {




  return `/auth/logout`
}

/**
 * Mencabut refresh token server-side dan menghapus cookie (idempotent)
 * @summary Logout
 */
export const postAuthLogout = async ( options?: RequestInit): Promise<postAuthLogoutResponse> => {

  return customInstance<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {


          return  postAuthLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>

    export type PostAuthLogoutMutationError = unknown

    /**
 * @summary Logout
 */
export const usePostAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
    }
    export type deleteAuthProvidersGoogleResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type deleteAuthProvidersGoogleResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type deleteAuthProvidersGoogleResponse409 = {
  data: DtoErrorResponse
  status: 409
}

export type deleteAuthProvidersGoogleResponseSuccess = (deleteAuthProvidersGoogleResponse200) & {
  headers: Headers;
};
export type deleteAuthProvidersGoogleResponseError = (deleteAuthProvidersGoogleResponse401 | deleteAuthProvidersGoogleResponse409) & {
  headers: Headers;
};

export type deleteAuthProvidersGoogleResponse = (deleteAuthProvidersGoogleResponseSuccess | deleteAuthProvidersGoogleResponseError)

export const getDeleteAuthProvidersGoogleUrl = () => {




  return `/auth/providers/google`
}

/**
 * Putuskan hubungan Google dari akun. Ditolak (409) bila ini
satu-satunya metode login (tanpa password & tanpa provider lain).
 * @summary Unlink Google provider
 */
export const deleteAuthProvidersGoogle = async ( options?: RequestInit): Promise<deleteAuthProvidersGoogleResponse> => {

  return customInstance<deleteAuthProvidersGoogleResponse>(getDeleteAuthProvidersGoogleUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteAuthProvidersGoogleMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthProvidersGoogle>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAuthProvidersGoogle>>, TError,void, TContext> => {

const mutationKey = ['deleteAuthProvidersGoogle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAuthProvidersGoogle>>, void> = () => {


          return  deleteAuthProvidersGoogle(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAuthProvidersGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAuthProvidersGoogle>>>

    export type DeleteAuthProvidersGoogleMutationError = DtoErrorResponse

    /**
 * @summary Unlink Google provider
 */
export const useDeleteAuthProvidersGoogle = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthProvidersGoogle>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAuthProvidersGoogle>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteAuthProvidersGoogleMutationOptions(options), queryClient);
    }
    export type postAuthRefreshResponse200 = {
  data: DtoRefreshTokenResponse
  status: 200
}

export type postAuthRefreshResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postAuthRefreshResponseSuccess = (postAuthRefreshResponse200) & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (postAuthRefreshResponse401) & {
  headers: Headers;
};

export type postAuthRefreshResponse = (postAuthRefreshResponseSuccess | postAuthRefreshResponseError)

export const getPostAuthRefreshUrl = () => {




  return `/auth/refresh`
}

/**
 * Memutar refresh token (httpOnly cookie) dan mengembalikan access token baru
 * @summary Refresh access token
 */
export const postAuthRefresh = async ( options?: RequestInit): Promise<postAuthRefreshResponse> => {

  return customInstance<postAuthRefreshResponse>(getPostAuthRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthRefreshMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,void, TContext> => {

const mutationKey = ['postAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, void> = () => {


          return  postAuthRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>

    export type PostAuthRefreshMutationError = DtoErrorResponse

    /**
 * @summary Refresh access token
 */
export const usePostAuthRefresh = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthRefreshMutationOptions(options), queryClient);
    }
    export type postAuthRegisterResponse201 = {
  data: DtoSuccessResponse
  status: 201
}

export type postAuthRegisterResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthRegisterResponse409 = {
  data: DtoErrorResponse
  status: 409
}

export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse201) & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (postAuthRegisterResponse400 | postAuthRegisterResponse409) & {
  headers: Headers;
};

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess | postAuthRegisterResponseError)

export const getPostAuthRegisterUrl = () => {




  return `/auth/register`
}

/**
 * Create a new user account (name, email, password)
 * @summary Register new user
 */
export const postAuthRegister = async (dtoCreateUserRequest: DtoCreateUserRequest, options?: RequestInit): Promise<postAuthRegisterResponse> => {

  return customInstance<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoCreateUserRequest,)
  }
);}




export const getPostAuthRegisterMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtoCreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtoCreateUserRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: DtoCreateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = DtoCreateUserRequest
    export type PostAuthRegisterMutationError = DtoErrorResponse

    /**
 * @summary Register new user
 */
export const usePostAuthRegister = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: DtoCreateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: DtoCreateUserRequest},
        TContext
      > => {
      return useMutation(getPostAuthRegisterMutationOptions(options), queryClient);
    }
    export type postAuthResendVerificationResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthResendVerificationResponseSuccess = (postAuthResendVerificationResponse200) & {
  headers: Headers;
};
;

export type postAuthResendVerificationResponse = (postAuthResendVerificationResponseSuccess)

export const getPostAuthResendVerificationUrl = () => {




  return `/auth/resend-verification`
}

/**
 * Kirim ulang link verifikasi. Respons selalu 200 (anti email-enumeration)
 * @summary Resend verification email
 */
export const postAuthResendVerification = async (dtoResendVerificationRequest: DtoResendVerificationRequest, options?: RequestInit): Promise<postAuthResendVerificationResponse> => {

  return customInstance<postAuthResendVerificationResponse>(getPostAuthResendVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoResendVerificationRequest,)
  }
);}




export const getPostAuthResendVerificationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResendVerification>>, TError,{data: DtoResendVerificationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthResendVerification>>, TError,{data: DtoResendVerificationRequest}, TContext> => {

const mutationKey = ['postAuthResendVerification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthResendVerification>>, {data: DtoResendVerificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthResendVerification(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthResendVerificationMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthResendVerification>>>
    export type PostAuthResendVerificationMutationBody = DtoResendVerificationRequest
    export type PostAuthResendVerificationMutationError = unknown

    /**
 * @summary Resend verification email
 */
export const usePostAuthResendVerification = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResendVerification>>, TError,{data: DtoResendVerificationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthResendVerification>>,
        TError,
        {data: DtoResendVerificationRequest},
        TContext
      > => {
      return useMutation(getPostAuthResendVerificationMutationOptions(options), queryClient);
    }
    export type postAuthResetPasswordResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthResetPasswordResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthResetPasswordResponseSuccess = (postAuthResetPasswordResponse200) & {
  headers: Headers;
};
export type postAuthResetPasswordResponseError = (postAuthResetPasswordResponse400) & {
  headers: Headers;
};

export type postAuthResetPasswordResponse = (postAuthResetPasswordResponseSuccess | postAuthResetPasswordResponseError)

export const getPostAuthResetPasswordUrl = () => {




  return `/auth/reset-password`
}

/**
 * Ganti password memakai kode reset; semua sesi lama dicabut
 * @summary Reset password
 */
export const postAuthResetPassword = async (dtoResetPasswordRequest: DtoResetPasswordRequest, options?: RequestInit): Promise<postAuthResetPasswordResponse> => {

  return customInstance<postAuthResetPasswordResponse>(getPostAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoResetPasswordRequest,)
  }
);}




export const getPostAuthResetPasswordMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,{data: DtoResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,{data: DtoResetPasswordRequest}, TContext> => {

const mutationKey = ['postAuthResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthResetPassword>>, {data: DtoResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthResetPassword>>>
    export type PostAuthResetPasswordMutationBody = DtoResetPasswordRequest
    export type PostAuthResetPasswordMutationError = DtoErrorResponse

    /**
 * @summary Reset password
 */
export const usePostAuthResetPassword = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,{data: DtoResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthResetPassword>>,
        TError,
        {data: DtoResetPasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthResetPasswordMutationOptions(options), queryClient);
    }
    export type getAuthSessionsResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getAuthSessionsResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getAuthSessionsResponseSuccess = (getAuthSessionsResponse200) & {
  headers: Headers;
};
export type getAuthSessionsResponseError = (getAuthSessionsResponse401) & {
  headers: Headers;
};

export type getAuthSessionsResponse = (getAuthSessionsResponseSuccess | getAuthSessionsResponseError)

export const getGetAuthSessionsUrl = () => {




  return `/auth/sessions`
}

/**
 * Daftar sesi aktif (device, IP, waktu). `current=true` untuk sesi ini.
 * @summary List active sessions
 */
export const getAuthSessions = async ( options?: RequestInit): Promise<getAuthSessionsResponse> => {

  return customInstance<getAuthSessionsResponse>(getGetAuthSessionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthSessionsQueryKey = () => {
    return [
    `/auth/sessions`
    ] as const;
    }


export const getGetAuthSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = DtoErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthSessions>>> = ({ signal }) => getAuthSessions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthSessions>>>
export type GetAuthSessionsQueryError = DtoErrorResponse


export function useGetAuthSessions<TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = DtoErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthSessions>>,
          TError,
          Awaited<ReturnType<typeof getAuthSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthSessions<TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthSessions>>,
          TError,
          Awaited<ReturnType<typeof getAuthSessions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthSessions<TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List active sessions
 */

export function useGetAuthSessions<TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthSessionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postAuthSessionsIdRevokeResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthSessionsIdRevokeResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postAuthSessionsIdRevokeResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type postAuthSessionsIdRevokeResponseSuccess = (postAuthSessionsIdRevokeResponse200) & {
  headers: Headers;
};
export type postAuthSessionsIdRevokeResponseError = (postAuthSessionsIdRevokeResponse401 | postAuthSessionsIdRevokeResponse404) & {
  headers: Headers;
};

export type postAuthSessionsIdRevokeResponse = (postAuthSessionsIdRevokeResponseSuccess | postAuthSessionsIdRevokeResponseError)

export const getPostAuthSessionsIdRevokeUrl = (id: number,) => {




  return `/auth/sessions/${id}/revoke`
}

/**
 * Putuskan satu sesi aktif by id (hanya milik user sendiri)
 * @summary Revoke one session
 */
export const postAuthSessionsIdRevoke = async (id: number, options?: RequestInit): Promise<postAuthSessionsIdRevokeResponse> => {

  return customInstance<postAuthSessionsIdRevokeResponse>(getPostAuthSessionsIdRevokeUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostAuthSessionsIdRevokeMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSessionsIdRevoke>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSessionsIdRevoke>>, TError,{id: number}, TContext> => {

const mutationKey = ['postAuthSessionsIdRevoke'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSessionsIdRevoke>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postAuthSessionsIdRevoke(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSessionsIdRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSessionsIdRevoke>>>

    export type PostAuthSessionsIdRevokeMutationError = DtoErrorResponse

    /**
 * @summary Revoke one session
 */
export const usePostAuthSessionsIdRevoke = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSessionsIdRevoke>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSessionsIdRevoke>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostAuthSessionsIdRevokeMutationOptions(options), queryClient);
    }
    export type postAuthSetPasswordResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthSetPasswordResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthSetPasswordResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type postAuthSetPasswordResponseSuccess = (postAuthSetPasswordResponse200) & {
  headers: Headers;
};
export type postAuthSetPasswordResponseError = (postAuthSetPasswordResponse400 | postAuthSetPasswordResponse401) & {
  headers: Headers;
};

export type postAuthSetPasswordResponse = (postAuthSetPasswordResponseSuccess | postAuthSetPasswordResponseError)

export const getPostAuthSetPasswordUrl = () => {




  return `/auth/set-password`
}

/**
 * Pasang password untuk akun tanpa password; semua sesi lain dicabut
 * @summary Set password (akun Google-only)
 */
export const postAuthSetPassword = async (dtoSetPasswordRequest: DtoSetPasswordRequest, options?: RequestInit): Promise<postAuthSetPasswordResponse> => {

  return customInstance<postAuthSetPasswordResponse>(getPostAuthSetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoSetPasswordRequest,)
  }
);}




export const getPostAuthSetPasswordMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSetPassword>>, TError,{data: DtoSetPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSetPassword>>, TError,{data: DtoSetPasswordRequest}, TContext> => {

const mutationKey = ['postAuthSetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSetPassword>>, {data: DtoSetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthSetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSetPassword>>>
    export type PostAuthSetPasswordMutationBody = DtoSetPasswordRequest
    export type PostAuthSetPasswordMutationError = DtoErrorResponse

    /**
 * @summary Set password (akun Google-only)
 */
export const usePostAuthSetPassword = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSetPassword>>, TError,{data: DtoSetPasswordRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSetPassword>>,
        TError,
        {data: DtoSetPasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthSetPasswordMutationOptions(options), queryClient);
    }
    export type postAuthVerifyEmailResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type postAuthVerifyEmailResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type postAuthVerifyEmailResponseSuccess = (postAuthVerifyEmailResponse200) & {
  headers: Headers;
};
export type postAuthVerifyEmailResponseError = (postAuthVerifyEmailResponse400) & {
  headers: Headers;
};

export type postAuthVerifyEmailResponse = (postAuthVerifyEmailResponseSuccess | postAuthVerifyEmailResponseError)

export const getPostAuthVerifyEmailUrl = () => {




  return `/auth/verify-email`
}

/**
 * Validasi kode verifikasi email dan menandai email terverifikasi
 * @summary Verify email
 */
export const postAuthVerifyEmail = async (dtoVerifyEmailRequest: DtoVerifyEmailRequest, options?: RequestInit): Promise<postAuthVerifyEmailResponse> => {

  return customInstance<postAuthVerifyEmailResponse>(getPostAuthVerifyEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoVerifyEmailRequest,)
  }
);}




export const getPostAuthVerifyEmailMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthVerifyEmail>>, TError,{data: DtoVerifyEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthVerifyEmail>>, TError,{data: DtoVerifyEmailRequest}, TContext> => {

const mutationKey = ['postAuthVerifyEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthVerifyEmail>>, {data: DtoVerifyEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthVerifyEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthVerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthVerifyEmail>>>
    export type PostAuthVerifyEmailMutationBody = DtoVerifyEmailRequest
    export type PostAuthVerifyEmailMutationError = DtoErrorResponse

    /**
 * @summary Verify email
 */
export const usePostAuthVerifyEmail = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthVerifyEmail>>, TError,{data: DtoVerifyEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthVerifyEmail>>,
        TError,
        {data: DtoVerifyEmailRequest},
        TContext
      > => {
      return useMutation(getPostAuthVerifyEmailMutationOptions(options), queryClient);
    }
    export type getUsersResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type getUsersResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type getUsersResponse404 = {
  data: DtoErrorResponse
  status: 404
}

export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
export type getUsersResponseError = (getUsersResponse401 | getUsersResponse404) & {
  headers: Headers;
};

export type getUsersResponse = (getUsersResponseSuccess | getUsersResponseError)

export const getGetUsersUrl = () => {




  return `/users`
}

/**
 * Get current logged in user profile based on JWT token
 * @summary Get user profile
 */
export const getUsers = async ( options?: RequestInit): Promise<getUsersResponse> => {

  return customInstance<getUsersResponse>(getGetUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersQueryKey = () => {
    return [
    `/users`
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = DtoErrorResponse


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user profile
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = DtoErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchUsersResponse200 = {
  data: DtoSuccessResponse
  status: 200
}

export type patchUsersResponse400 = {
  data: DtoErrorResponse
  status: 400
}

export type patchUsersResponse401 = {
  data: DtoErrorResponse
  status: 401
}

export type patchUsersResponseSuccess = (patchUsersResponse200) & {
  headers: Headers;
};
export type patchUsersResponseError = (patchUsersResponse400 | patchUsersResponse401) & {
  headers: Headers;
};

export type patchUsersResponse = (patchUsersResponseSuccess | patchUsersResponseError)

export const getPatchUsersUrl = () => {




  return `/users`
}

/**
 * Edit nama user yang sedang login. Email/role tidak berubah.
 * @summary Update profile (name)
 */
export const patchUsers = async (dtoUpdateUserRequest: DtoUpdateUserRequest, options?: RequestInit): Promise<patchUsersResponse> => {

  return customInstance<patchUsersResponse>(getPatchUsersUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      dtoUpdateUserRequest,)
  }
);}




export const getPatchUsersMutationOptions = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsers>>, TError,{data: DtoUpdateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchUsers>>, TError,{data: DtoUpdateUserRequest}, TContext> => {

const mutationKey = ['patchUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUsers>>, {data: DtoUpdateUserRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchUsers(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchUsersMutationResult = NonNullable<Awaited<ReturnType<typeof patchUsers>>>
    export type PatchUsersMutationBody = DtoUpdateUserRequest
    export type PatchUsersMutationError = DtoErrorResponse

    /**
 * @summary Update profile (name)
 */
export const usePatchUsers = <TError = DtoErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsers>>, TError,{data: DtoUpdateUserRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUsers>>,
        TError,
        {data: DtoUpdateUserRequest},
        TContext
      > => {
      return useMutation(getPatchUsersMutationOptions(options), queryClient);
    }
